### ISSUE TITLE
No Module named Audioop

### ISSUE THREAD

**Issue by Benchmark137** [Iimboo/Encompass-Discord-Bot#1]
The script does not work, when attempting to start the bot on CMD it cannot find module named audioop

**Comment by Nabeyo** [comment]
It's an issue with the newest version of python rather than the code. Running "pip install audioop-lts" in cmd before launching the bot worked for me.

**Comment by Iimboo** [comment]
I'll have to include that into the ReadME, thanks!!

**Comment by smithmatthews** [comment]
I ran into this issue as well and the solution noted by Nabeyo worked.  Everything else worked as expected.

References
https://docs.python.org/3/library/audioop.html
_Deprecated since version 3.11, removed in version 3.13._

https://peps.python.org/pep-0594/
Python 3.13.1
