### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by Klambell** [Iimboo/Encompass-Discord-Bot#3]
Hi, I was stuck when running Encompass.py and it said " AttributeError: 'NoneType' object has no attribute 'send' " How can I fix that?
![image](https://github.com/user-attachments/assets/5d349acd-1065-4826-af9f-d8bf6da460c7)

**Comment by Iimboo** [comment]
I'm pretty sure that's because you didn't set up the channel_id properly in config.py
it should look like this for reference: "CHANNEL_ID = 1247454682190250240"

**Comment by Klambell** [comment]
Oh tysm! it's already fixed.
